import os

DEFAULT_DATASETS_DIR = os.path.join(os.getcwd(), "data/")

P_VALUE_THRESHOLD = 0.05

FREQ_DICT = {
    'Annual': 'A',
    'Monthly': 'M',
    'Month Start': 'MS',
    'Month End': 'M',
    'Daily': 'D',
    'Weekly': 'W',
    'Bi-Monthly': '2M',
    'Quarterly': 'Q',
    'Semi-Annually': '6M',
    'Bi-Weekly': 'BM',
    'Quarterly Start': 'BQ',
    'Annual Start': 'BA',
    'Annual End': 'A',
    'Quarterly Start of Business': 'BQS',
    'Semi-Annual Start of Business': 'BAS',
    'Annual Start of Business Week': 'BAS-DEC',
    'Week End': 'W-SUN',
    'Custom Week End': 'W-MON',
    'Custom Week End': 'W-TUE',
    'Custom Week End': 'W-WED',
    'Custom Week End': 'W-THU',
    'Custom Week End': 'W-FRI',
    'Custom Week End': 'W-SAT',
    'Custom Week End': 'W',
    'Custom Week Start': 'W-MON',
    'Custom Week Start': 'W-TUE',
    'Custom Week Start': 'W-WED',
    'Custom Week Start': 'W-THU',
    'Custom Week Start': 'W-FRI',
    'Custom Week Start': 'W-SAT',
    'Custom Week Start': 'W',
    'Business Day': 'B',
    'Business Day Start': 'BAS',
    'Business Day Start of Month': 'BMS',
    'Business Day Start of Quarter': 'BQS',
    'Business Day End': 'B',
    'Business Day End of Month': 'BM',
    'Business Day End of Quarter': 'BQ',
    'Hourly':'H',
    'Minutely':'T',
    'Secondly':'S',
    'Milliseconds':'ms',
    'Microseconds':'U',
    'Nanoseconds':'N'
}
